<?php
# automatically generated by makeclasses.php

class AccessRelation extends Relation {
	function __construct() {
		parent::__construct(
			RaDB::$db, 
			# $this->schema: for building forms among other things
			array (
			  'surveyid' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'key' => true,
			    'null' => false,
			    'default' => '0',
			    'name' => 'surveyid',
			    'extra' => '',
			  ),
			  'userid' => 
			  array (
			    'type' => 'varchar',
			    'size' => '64',
			    'key' => true,
			    'null' => false,
			    'default' => '',
			    'name' => 'userid',
			    'extra' => '',
			  ),
			  'role' => 
			  array (
			    'type' => 'varchar',
			    'size' => '64',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'role',
			    'extra' => '',
			  ),
			  'PRIMARY KEY' => 
			  array (
			    'surveyid' => '',
			    'userid' => '',
			  ),
			),
			'access'
		);
	}

}
