<?php
# automatically generated by makeclasses.php

class MysectionsRelation extends Relation {
	function __construct() {
		parent::__construct(
			RaDB::$db, 
			# $this->schema: for building forms among other things
			array (
			  'sectionid' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'null' => false,
			    'default' => '0',
			    'name' => 'sectionid',
			    'extra' => '',
			  ),
			  'name' => 
			  array (
			    'type' => 'varchar',
			    'size' => '255',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'name',
			    'extra' => '',
			  ),
			  'raw' => 
			  array (
			    'type' => 'longtext',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'raw',
			    'extra' => '',
			  ),
			  'php' => 
			  array (
			    'type' => 'longtext',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'php',
			    'extra' => '',
			  ),
			  'json' => 
			  array (
			    'type' => 'longtext',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'json',
			    'extra' => '',
			  ),
			  'userid' => 
			  array (
			    'type' => 'varchar',
			    'size' => '64',
			    'null' => false,
			    'default' => '',
			    'name' => 'userid',
			    'extra' => '',
			  ),
			  'role' => 
			  array (
			    'type' => 'varchar',
			    'size' => '64',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'role',
			    'extra' => '',
			  ),
			  'surveyhide' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'null' => false,
			    'default' => '0',
			    'name' => 'surveyhide',
			    'extra' => '',
			  ),
			  'visible' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'null' => false,
			    'default' => '0',
			    'name' => 'visible',
			    'extra' => '',
			  ),
			  'ord' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'null' => false,
			    'default' => '0',
			    'name' => 'ord',
			    'extra' => '',
			  ),
			  'PRIMARY KEY' => 
			  array (
			  ),
			),
			'mysections'
		);
	}

}
