<?php
# automatically generated by makeclasses.php

class MysurveysectionsRelation extends Relation {
	function __construct() {
		parent::__construct(
			RaDB::$db, 
			# $this->schema: for building forms among other things
			array (
			  'surveyid' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'null' => false,
			    'default' => '0',
			    'name' => 'surveyid',
			    'extra' => '',
			  ),
			  'title' => 
			  array (
			    'type' => 'varchar',
			    'size' => '255',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'title',
			    'extra' => '',
			  ),
			  'sectionid' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'null' => true,
			    'default' => '0',
			    'name' => 'sectionid',
			    'extra' => '',
			  ),
			  'name' => 
			  array (
			    'type' => 'varchar',
			    'size' => '255',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'name',
			    'extra' => '',
			  ),
			  'userid' => 
			  array (
			    'type' => 'varchar',
			    'size' => '64',
			    'null' => false,
			    'default' => '',
			    'name' => 'userid',
			    'extra' => '',
			  ),
			  'role' => 
			  array (
			    'type' => 'varchar',
			    'size' => '64',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'role',
			    'extra' => '',
			  ),
			  'visible' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'null' => true,
			    'default' => '0',
			    'name' => 'visible',
			    'extra' => '',
			  ),
			  'ord' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'null' => true,
			    'default' => '0',
			    'name' => 'ord',
			    'extra' => '',
			  ),
			  'hide' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'null' => false,
			    'default' => '0',
			    'name' => 'hide',
			    'extra' => '',
			  ),
			  'PRIMARY KEY' => 
			  array (
			  ),
			),
			'mysurveysections'
		);
	}

}
