<?php
# automatically generated by makeclasses.php

class SaverstateRelation extends Relation {
	function __construct() {
		parent::__construct(
			RaDB::$db, 
			# $this->schema: for building forms among other things
			array (
			  'partid' => 
			  array (
			    'type' => 'varchar',
			    'size' => '128',
			    'key' => true,
			    'null' => false,
			    'default' => NULL,
			    'name' => 'partid',
			    'extra' => '',
			  ),
			  'survey' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'key' => true,
			    'null' => false,
			    'default' => NULL,
			    'name' => 'survey',
			    'extra' => '',
			  ),
			  'section' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'key' => true,
			    'null' => false,
			    'default' => NULL,
			    'name' => 'section',
			    'extra' => '',
			  ),
			  'lastq' => 
			  array (
			    'type' => 'text',
			    'null' => false,
			    'default' => NULL,
			    'name' => 'lastq',
			    'extra' => '',
			  ),
			  'state' => 
			  array (
			    'type' => 'text',
			    'null' => false,
			    'default' => NULL,
			    'name' => 'state',
			    'extra' => '',
			  ),
			  'modified' => 
			  array (
			    'type' => 'datetime',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'modified',
			    'extra' => '',
			  ),
			  'sent' => 
			  array (
			    'type' => 'datetime',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'sent',
			    'extra' => '',
			  ),
			  'PRIMARY KEY' => 
			  array (
			    'partid' => '',
			    'survey' => '',
			    'section' => '',
			  ),
			),
			'saverstate'
		);
	}

}
