<?php
# automatically generated by makeclasses.php

class SurveyEntity extends Entity {
	function __construct() {
		parent::__construct(
			RaDB::$db, 
			# $this->schema: for building forms among other things
			array (
			  'surveyid' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'auto' => true,
			    'key' => true,
			    'null' => false,
			    'default' => NULL,
			    'name' => 'surveyid',
			    'extra' => 'auto_increment',
			  ),
			  'title' => 
			  array (
			    'type' => 'varchar',
			    'size' => '255',
			    'null' => true,
			    'default' => NULL,
			    'name' => 'title',
			    'extra' => '',
			  ),
			  'hide' => 
			  array (
			    'type' => 'int',
			    'size' => '11',
			    'null' => false,
			    'default' => '0',
			    'name' => 'hide',
			    'extra' => '',
			  ),
			),
			'survey'
		);
	}

}
